# Generated by Django 5.1.6 on 2025-03-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('vet', 'Veterinarian'), ('receptionist', 'Receptionist'), ('owner', 'Pet Owner')], max_length=100),
        ),
    ]
